local _, NS = ...

local L = {
    TITLE="lafee bdk bones stacks", SETTINGS="Settings", GENERAL="General", TRACKERS="Trackers", POSITIONING="Positioning", APPEARANCE="Appearance",
    OPEN_HINT="Open this menu from the minimap launcher or with /las.", SHOW_MINIMAP="Show minimap button", SAFE_AURA_DISPLAY="Safe aura display",
    SAFE_LINE_1="Application counts are written directly by Blizzard to the text widget.", SAFE_LINE_2="The addon never reads or formats aura stack values in Lua.",
    AURA_TRACKERS="Aura trackers", NEW="New", DUPLICATE="Duplicate", DELETE="Delete", PREVIEW="Preview", UNLOCK="Unlock",
    TRACKER_SETTINGS="Tracker settings", NAME="Name", AURA_IDS="Aura IDs", UNIT="Unit", ENABLED="Enabled", HIDE_WHEN_MISSING="Hide when missing",
    APPLY_TRACKER="Apply tracker", SELECTED_TRACKER="Selected tracker: %s", CURSOR_OFFSET="Cursor offset",
    CURSOR_OFFSET_DESC="Place the stack counter around the mouse pointer.", OFFSET_X="Offset X", OFFSET_Y="Offset Y",
    TEXT_APPEARANCE="Text appearance", TEXT_APPEARANCE_DESC="Choose the size, outline, and colour of the stack number.", FONT="Font",
    TEXT_SIZE="Text size", OUTLINE_LABEL="Outline", NONE="None", OUTLINE="Outline", THICK_OUTLINE="Thick outline", TEXT_COLOUR="Text colour",
    AURA_DURATION="Aura duration", AURA_DURATION_DESC="Choose a bar below the number or a radial cooldown around the cursor.",
    PROGRESS_DISPLAY="Progress display", HORIZONTAL_BAR="Horizontal bar", CIRCLE_AROUND_CURSOR="Circle around cursor",
    BAR_WIDTH="Bar width", BAR_HEIGHT="Bar height", CIRCLE_SIZE="Circle size", CIRCLE_THICKNESS="Circle thickness", PROGRESS_COLOUR="Progress colour",
    COLOUR="Colour", OPEN_MENU_DESC="Open the addon menu with the button below.", OPEN_MENU="Open lafee bdk bones stacks",
    MINIMAP_TOOLTIP="Left-click to open settings.", BONE_SHIELD="Bone Shield", AURA_STACKS="Aura Stacks", COPY_SUFFIX=" Copy",
}

local translations = {
    frFR = {
        SETTINGS="Réglages", GENERAL="Général", TRACKERS="Suivis", POSITIONING="Positionnement", APPEARANCE="Apparence",
        OPEN_HINT="Ouvrez ce menu depuis la minicarte ou avec /las.", SHOW_MINIMAP="Afficher le bouton de la minicarte",
        SAFE_AURA_DISPLAY="Affichage sécurisé des auras", SAFE_LINE_1="Le nombre d’applications est écrit directement par Blizzard dans le texte.",
        SAFE_LINE_2="L’addon ne lit ni ne formate jamais les charges d’aura en Lua.", AURA_TRACKERS="Suivis d’auras", NEW="Nouveau",
        DUPLICATE="Dupliquer", DELETE="Supprimer", PREVIEW="Aperçu", UNLOCK="Déverrouiller", TRACKER_SETTINGS="Réglages du suivi",
        NAME="Nom", AURA_IDS="ID des auras", UNIT="Unité", ENABLED="Activé", HIDE_WHEN_MISSING="Masquer si absente", APPLY_TRACKER="Appliquer",
        SELECTED_TRACKER="Suivi sélectionné : %s", CURSOR_OFFSET="Décalage du curseur", CURSOR_OFFSET_DESC="Placez le compteur de charges autour du pointeur.",
        OFFSET_X="Décalage X", OFFSET_Y="Décalage Y", TEXT_APPEARANCE="Apparence du texte",
        TEXT_APPEARANCE_DESC="Choisissez la taille, le contour et la couleur du nombre de charges.", FONT="Police", TEXT_SIZE="Taille du texte",
        OUTLINE_LABEL="Contour", NONE="Aucun", OUTLINE="Contour", THICK_OUTLINE="Contour épais", TEXT_COLOUR="Couleur du texte",
        AURA_DURATION="Durée de l’aura", AURA_DURATION_DESC="Choisissez une barre sous le nombre ou un temps de recharge radial autour du curseur.",
        PROGRESS_DISPLAY="Affichage de la progression", HORIZONTAL_BAR="Barre horizontale", CIRCLE_AROUND_CURSOR="Cercle autour du curseur",
        BAR_WIDTH="Largeur de la barre", BAR_HEIGHT="Hauteur de la barre", CIRCLE_SIZE="Taille du cercle", CIRCLE_THICKNESS="Épaisseur du cercle",
        PROGRESS_COLOUR="Couleur de progression", COLOUR="Couleur", OPEN_MENU_DESC="Ouvrez le menu de l’addon avec le bouton ci-dessous.",
        OPEN_MENU="Ouvrir lafee bdk bones stacks", MINIMAP_TOOLTIP="Clic gauche pour ouvrir les réglages.", BONE_SHIELD="Bouclier d’os",
        AURA_STACKS="Charges d’aura", COPY_SUFFIX=" - copie",
    },
    deDE = {
        SETTINGS="Einstellungen", GENERAL="Allgemein", TRACKERS="Tracker", POSITIONING="Positionierung", APPEARANCE="Aussehen",
        OPEN_HINT="Öffne dieses Menü über die Minikarte oder mit /las.", SHOW_MINIMAP="Minikartenschaltfläche anzeigen", SAFE_AURA_DISPLAY="Sichere Auraanzeige",
        SAFE_LINE_1="Blizzard schreibt die Anwendungsanzahl direkt in das Textfeld.", SAFE_LINE_2="Das Addon liest oder formatiert Aurastapel niemals in Lua.",
        AURA_TRACKERS="Aura-Tracker", NEW="Neu", DUPLICATE="Duplizieren", DELETE="Löschen", PREVIEW="Vorschau", UNLOCK="Entsperren",
        TRACKER_SETTINGS="Tracker-Einstellungen", NAME="Name", AURA_IDS="Aura-IDs", UNIT="Einheit", ENABLED="Aktiviert",
        HIDE_WHEN_MISSING="Ausblenden, wenn nicht vorhanden", APPLY_TRACKER="Tracker anwenden", SELECTED_TRACKER="Ausgewählter Tracker: %s",
        CURSOR_OFFSET="Cursorversatz", CURSOR_OFFSET_DESC="Platziere den Stapelzähler um den Mauszeiger.", OFFSET_X="X-Versatz", OFFSET_Y="Y-Versatz",
        TEXT_APPEARANCE="Textdarstellung", TEXT_APPEARANCE_DESC="Wähle Größe, Kontur und Farbe der Stapelzahl.", FONT="Schriftart",
        TEXT_SIZE="Textgröße", OUTLINE_LABEL="Kontur", NONE="Keine", OUTLINE="Kontur", THICK_OUTLINE="Dicke Kontur", TEXT_COLOUR="Textfarbe",
        AURA_DURATION="Auradauer", AURA_DURATION_DESC="Wähle eine Leiste unter der Zahl oder eine radiale Abklingzeit um den Cursor.",
        PROGRESS_DISPLAY="Fortschrittsanzeige", HORIZONTAL_BAR="Horizontale Leiste", CIRCLE_AROUND_CURSOR="Kreis um den Cursor",
        BAR_WIDTH="Leistenbreite", BAR_HEIGHT="Leistenhöhe", CIRCLE_SIZE="Kreisgröße", CIRCLE_THICKNESS="Kreisdicke", PROGRESS_COLOUR="Fortschrittsfarbe",
        COLOUR="Farbe", OPEN_MENU_DESC="Öffne das Addon-Menü mit der Schaltfläche unten.", OPEN_MENU="lafee bdk bones stacks öffnen",
        MINIMAP_TOOLTIP="Linksklick zum Öffnen der Einstellungen.", BONE_SHIELD="Knochenschild", AURA_STACKS="Aurastapel", COPY_SUFFIX=" – Kopie",
    },
    esES = {
        SETTINGS="Ajustes", GENERAL="General", TRACKERS="Rastreadores", POSITIONING="Posición", APPEARANCE="Apariencia",
        OPEN_HINT="Abre este menú desde el botón del minimapa o con /las.", SHOW_MINIMAP="Mostrar botón del minimapa", SAFE_AURA_DISPLAY="Visualización segura de auras",
        SAFE_LINE_1="Blizzard escribe directamente el número de aplicaciones en el texto.", SAFE_LINE_2="El addon nunca lee ni formatea las acumulaciones de aura en Lua.",
        AURA_TRACKERS="Rastreadores de auras", NEW="Nuevo", DUPLICATE="Duplicar", DELETE="Eliminar", PREVIEW="Vista previa", UNLOCK="Desbloquear",
        TRACKER_SETTINGS="Ajustes del rastreador", NAME="Nombre", AURA_IDS="ID de aura", UNIT="Unidad", ENABLED="Activado",
        HIDE_WHEN_MISSING="Ocultar si no está presente", APPLY_TRACKER="Aplicar rastreador", SELECTED_TRACKER="Rastreador seleccionado: %s",
        CURSOR_OFFSET="Desplazamiento del cursor", CURSOR_OFFSET_DESC="Coloca el contador de acumulaciones alrededor del puntero.",
        OFFSET_X="Desplazamiento X", OFFSET_Y="Desplazamiento Y", TEXT_APPEARANCE="Apariencia del texto",
        TEXT_APPEARANCE_DESC="Elige el tamaño, contorno y color del número de acumulaciones.", FONT="Fuente", TEXT_SIZE="Tamaño del texto",
        OUTLINE_LABEL="Contorno", NONE="Ninguno", OUTLINE="Contorno", THICK_OUTLINE="Contorno grueso", TEXT_COLOUR="Color del texto",
        AURA_DURATION="Duración del aura", AURA_DURATION_DESC="Elige una barra bajo el número o un tiempo de reutilización radial alrededor del cursor.",
        PROGRESS_DISPLAY="Visualización del progreso", HORIZONTAL_BAR="Barra horizontal", CIRCLE_AROUND_CURSOR="Círculo alrededor del cursor",
        BAR_WIDTH="Ancho de la barra", BAR_HEIGHT="Alto de la barra", CIRCLE_SIZE="Tamaño del círculo", CIRCLE_THICKNESS="Grosor del círculo",
        PROGRESS_COLOUR="Color del progreso", COLOUR="Color", OPEN_MENU_DESC="Abre el menú del addon con el botón inferior.",
        OPEN_MENU="Abrir lafee bdk bones stacks", MINIMAP_TOOLTIP="Clic izquierdo para abrir los ajustes.", BONE_SHIELD="Escudo óseo",
        AURA_STACKS="Acumulaciones de aura", COPY_SUFFIX=" - copia",
    },
    itIT = {
        SETTINGS="Impostazioni", GENERAL="Generale", TRACKERS="Tracciatori", POSITIONING="Posizionamento", APPEARANCE="Aspetto",
        OPEN_HINT="Apri questo menu dal pulsante della minimappa o con /las.", SHOW_MINIMAP="Mostra pulsante della minimappa", SAFE_AURA_DISPLAY="Visualizzazione sicura delle aure",
        SAFE_LINE_1="Blizzard scrive direttamente il numero di applicazioni nel testo.", SAFE_LINE_2="L’addon non legge né formatta mai le cariche dell’aura in Lua.",
        AURA_TRACKERS="Tracciatori di aure", NEW="Nuovo", DUPLICATE="Duplica", DELETE="Elimina", PREVIEW="Anteprima", UNLOCK="Sblocca",
        TRACKER_SETTINGS="Impostazioni tracciatore", NAME="Nome", AURA_IDS="ID aura", UNIT="Unità", ENABLED="Attivo",
        HIDE_WHEN_MISSING="Nascondi se assente", APPLY_TRACKER="Applica tracciatore", SELECTED_TRACKER="Tracciatore selezionato: %s",
        CURSOR_OFFSET="Offset cursore", CURSOR_OFFSET_DESC="Posiziona il contatore di cariche attorno al puntatore.", OFFSET_X="Offset X", OFFSET_Y="Offset Y",
        TEXT_APPEARANCE="Aspetto del testo", TEXT_APPEARANCE_DESC="Scegli dimensione, contorno e colore del numero di cariche.", FONT="Carattere",
        TEXT_SIZE="Dimensione testo", OUTLINE_LABEL="Contorno", NONE="Nessuno", OUTLINE="Contorno", THICK_OUTLINE="Contorno spesso", TEXT_COLOUR="Colore testo",
        AURA_DURATION="Durata aura", AURA_DURATION_DESC="Scegli una barra sotto il numero o un recupero radiale attorno al cursore.",
        PROGRESS_DISPLAY="Visualizzazione progresso", HORIZONTAL_BAR="Barra orizzontale", CIRCLE_AROUND_CURSOR="Cerchio attorno al cursore",
        BAR_WIDTH="Larghezza barra", BAR_HEIGHT="Altezza barra", CIRCLE_SIZE="Dimensione cerchio", CIRCLE_THICKNESS="Spessore cerchio",
        PROGRESS_COLOUR="Colore progresso", COLOUR="Colore", OPEN_MENU_DESC="Apri il menu dell’addon con il pulsante qui sotto.",
        OPEN_MENU="Apri lafee bdk bones stacks", MINIMAP_TOOLTIP="Clic sinistro per aprire le impostazioni.", BONE_SHIELD="Scudo d’Ossa",
        AURA_STACKS="Cariche aura", COPY_SUFFIX=" - copia",
    },
    ptBR = {
        SETTINGS="Configurações", GENERAL="Geral", TRACKERS="Rastreadores", POSITIONING="Posicionamento", APPEARANCE="Aparência",
        OPEN_HINT="Abra este menu pelo botão do minimapa ou com /las.", SHOW_MINIMAP="Mostrar botão do minimapa", SAFE_AURA_DISPLAY="Exibição segura de auras",
        SAFE_LINE_1="A Blizzard escreve diretamente o número de aplicações no texto.", SAFE_LINE_2="O addon nunca lê nem formata acúmulos de aura em Lua.",
        AURA_TRACKERS="Rastreadores de aura", NEW="Novo", DUPLICATE="Duplicar", DELETE="Excluir", PREVIEW="Prévia", UNLOCK="Desbloquear",
        TRACKER_SETTINGS="Configurações do rastreador", NAME="Nome", AURA_IDS="IDs de aura", UNIT="Unidade", ENABLED="Ativado",
        HIDE_WHEN_MISSING="Ocultar quando ausente", APPLY_TRACKER="Aplicar rastreador", SELECTED_TRACKER="Rastreador selecionado: %s",
        CURSOR_OFFSET="Deslocamento do cursor", CURSOR_OFFSET_DESC="Posicione o contador de acúmulos ao redor do ponteiro.",
        OFFSET_X="Deslocamento X", OFFSET_Y="Deslocamento Y", TEXT_APPEARANCE="Aparência do texto",
        TEXT_APPEARANCE_DESC="Escolha o tamanho, contorno e cor do número de acúmulos.", FONT="Fonte", TEXT_SIZE="Tamanho do texto",
        OUTLINE_LABEL="Contorno", NONE="Nenhum", OUTLINE="Contorno", THICK_OUTLINE="Contorno grosso", TEXT_COLOUR="Cor do texto",
        AURA_DURATION="Duração da aura", AURA_DURATION_DESC="Escolha uma barra sob o número ou uma recarga radial ao redor do cursor.",
        PROGRESS_DISPLAY="Exibição do progresso", HORIZONTAL_BAR="Barra horizontal", CIRCLE_AROUND_CURSOR="Círculo ao redor do cursor",
        BAR_WIDTH="Largura da barra", BAR_HEIGHT="Altura da barra", CIRCLE_SIZE="Tamanho do círculo", CIRCLE_THICKNESS="Espessura do círculo",
        PROGRESS_COLOUR="Cor do progresso", COLOUR="Cor", OPEN_MENU_DESC="Abra o menu do addon com o botão abaixo.",
        OPEN_MENU="Abrir lafee bdk bones stacks", MINIMAP_TOOLTIP="Clique esquerdo para abrir as configurações.", BONE_SHIELD="Escudo Ósseo",
        AURA_STACKS="Acúmulos de aura", COPY_SUFFIX=" - cópia",
    },
    ruRU = {
        SETTINGS="Настройки", GENERAL="Общие", TRACKERS="Отслеживание", POSITIONING="Позиционирование", APPEARANCE="Внешний вид",
        OPEN_HINT="Откройте это меню кнопкой у миникарты или командой /las.", SHOW_MINIMAP="Показывать кнопку у миникарты", SAFE_AURA_DISPLAY="Безопасное отображение аур",
        SAFE_LINE_1="Blizzard напрямую записывает число наложений в текстовый элемент.", SAFE_LINE_2="Аддон никогда не считывает и не форматирует стаки аур в Lua.",
        AURA_TRACKERS="Отслеживание аур", NEW="Создать", DUPLICATE="Дублировать", DELETE="Удалить", PREVIEW="Предпросмотр", UNLOCK="Разблокировать",
        TRACKER_SETTINGS="Настройки отслеживания", NAME="Название", AURA_IDS="ID аур", UNIT="Цель", ENABLED="Включено",
        HIDE_WHEN_MISSING="Скрывать при отсутствии", APPLY_TRACKER="Применить", SELECTED_TRACKER="Выбрано: %s",
        CURSOR_OFFSET="Смещение от курсора", CURSOR_OFFSET_DESC="Разместите счётчик стаков вокруг указателя мыши.", OFFSET_X="Смещение X", OFFSET_Y="Смещение Y",
        TEXT_APPEARANCE="Вид текста", TEXT_APPEARANCE_DESC="Выберите размер, обводку и цвет числа стаков.", FONT="Шрифт", TEXT_SIZE="Размер текста",
        OUTLINE_LABEL="Обводка", NONE="Нет", OUTLINE="Обводка", THICK_OUTLINE="Толстая обводка", TEXT_COLOUR="Цвет текста",
        AURA_DURATION="Длительность ауры", AURA_DURATION_DESC="Выберите полосу под числом или радиальный таймер вокруг курсора.",
        PROGRESS_DISPLAY="Индикатор прогресса", HORIZONTAL_BAR="Горизонтальная полоса", CIRCLE_AROUND_CURSOR="Круг вокруг курсора",
        BAR_WIDTH="Ширина полосы", BAR_HEIGHT="Высота полосы", CIRCLE_SIZE="Размер круга", CIRCLE_THICKNESS="Толщина круга",
        PROGRESS_COLOUR="Цвет прогресса", COLOUR="Цвет", OPEN_MENU_DESC="Откройте меню аддона кнопкой ниже.",
        OPEN_MENU="Открыть lafee bdk bones stacks", MINIMAP_TOOLTIP="ЛКМ: открыть настройки.", BONE_SHIELD="Костяной щит",
        AURA_STACKS="Стаки ауры", COPY_SUFFIX=" — копия",
    },
    koKR = {
        SETTINGS="설정", GENERAL="일반", TRACKERS="추적기", POSITIONING="위치", APPEARANCE="외형",
        OPEN_HINT="미니맵 버튼 또는 /las 명령어로 이 메뉴를 여세요.", SHOW_MINIMAP="미니맵 버튼 표시", SAFE_AURA_DISPLAY="안전한 오라 표시",
        SAFE_LINE_1="중첩 수는 블리자드가 텍스트 위젯에 직접 기록합니다.", SAFE_LINE_2="애드온은 Lua에서 오라 중첩 값을 읽거나 변환하지 않습니다.",
        AURA_TRACKERS="오라 추적기", NEW="새로 만들기", DUPLICATE="복제", DELETE="삭제", PREVIEW="미리보기", UNLOCK="잠금 해제",
        TRACKER_SETTINGS="추적기 설정", NAME="이름", AURA_IDS="오라 ID", UNIT="유닛", ENABLED="사용", HIDE_WHEN_MISSING="없을 때 숨기기",
        APPLY_TRACKER="추적기 적용", SELECTED_TRACKER="선택한 추적기: %s", CURSOR_OFFSET="커서 오프셋",
        CURSOR_OFFSET_DESC="마우스 포인터 주위에 중첩 카운터를 배치합니다.", OFFSET_X="X 오프셋", OFFSET_Y="Y 오프셋",
        TEXT_APPEARANCE="텍스트 외형", TEXT_APPEARANCE_DESC="중첩 숫자의 크기, 외곽선, 색상을 선택합니다.", FONT="글꼴", TEXT_SIZE="텍스트 크기",
        OUTLINE_LABEL="외곽선", NONE="없음", OUTLINE="외곽선", THICK_OUTLINE="굵은 외곽선", TEXT_COLOUR="텍스트 색상",
        AURA_DURATION="오라 지속시간", AURA_DURATION_DESC="숫자 아래 막대 또는 커서 주변 원형 재사용 대기시간을 선택합니다.",
        PROGRESS_DISPLAY="진행 표시", HORIZONTAL_BAR="가로 막대", CIRCLE_AROUND_CURSOR="커서 주변 원", BAR_WIDTH="막대 너비",
        BAR_HEIGHT="막대 높이", CIRCLE_SIZE="원 크기", CIRCLE_THICKNESS="원 두께", PROGRESS_COLOUR="진행 색상", COLOUR="색상",
        OPEN_MENU_DESC="아래 버튼으로 애드온 메뉴를 여세요.", OPEN_MENU="lafee bdk bones stacks 열기", MINIMAP_TOOLTIP="왼쪽 클릭으로 설정을 엽니다.",
        BONE_SHIELD="뼈의 보호막", AURA_STACKS="오라 중첩", COPY_SUFFIX=" 복사본",
    },
    zhCN = {
        SETTINGS="设置", GENERAL="常规", TRACKERS="追踪器", POSITIONING="定位", APPEARANCE="外观",
        OPEN_HINT="通过小地图按钮或输入 /las 打开此菜单。", SHOW_MINIMAP="显示小地图按钮", SAFE_AURA_DISPLAY="安全光环显示",
        SAFE_LINE_1="叠加层数由暴雪直接写入文本控件。", SAFE_LINE_2="插件不会在 Lua 中读取或格式化光环层数。", AURA_TRACKERS="光环追踪器",
        NEW="新建", DUPLICATE="复制", DELETE="删除", PREVIEW="预览", UNLOCK="解锁", TRACKER_SETTINGS="追踪器设置", NAME="名称",
        AURA_IDS="光环 ID", UNIT="单位", ENABLED="启用", HIDE_WHEN_MISSING="缺失时隐藏", APPLY_TRACKER="应用追踪器",
        SELECTED_TRACKER="已选追踪器：%s", CURSOR_OFFSET="鼠标偏移", CURSOR_OFFSET_DESC="将层数计数器放置在鼠标指针周围。",
        OFFSET_X="X 偏移", OFFSET_Y="Y 偏移", TEXT_APPEARANCE="文本外观", TEXT_APPEARANCE_DESC="选择层数数字的大小、描边和颜色。",
        FONT="字体", TEXT_SIZE="文本大小", OUTLINE_LABEL="描边", NONE="无", OUTLINE="描边", THICK_OUTLINE="粗描边", TEXT_COLOUR="文本颜色",
        AURA_DURATION="光环持续时间", AURA_DURATION_DESC="选择数字下方的进度条或鼠标周围的环形冷却。", PROGRESS_DISPLAY="进度显示",
        HORIZONTAL_BAR="水平条", CIRCLE_AROUND_CURSOR="鼠标周围圆环", BAR_WIDTH="进度条宽度", BAR_HEIGHT="进度条高度",
        CIRCLE_SIZE="圆环大小", CIRCLE_THICKNESS="圆环粗细", PROGRESS_COLOUR="进度颜色", COLOUR="颜色",
        OPEN_MENU_DESC="使用下方按钮打开插件菜单。", OPEN_MENU="打开 lafee bdk bones stacks", MINIMAP_TOOLTIP="左键点击打开设置。",
        BONE_SHIELD="白骨之盾", AURA_STACKS="光环层数", COPY_SUFFIX=" 副本",
    },
    zhTW = {
        SETTINGS="設定", GENERAL="一般", TRACKERS="追蹤器", POSITIONING="定位", APPEARANCE="外觀",
        OPEN_HINT="透過小地圖按鈕或輸入 /las 開啟此選單。", SHOW_MINIMAP="顯示小地圖按鈕", SAFE_AURA_DISPLAY="安全光環顯示",
        SAFE_LINE_1="疊加層數由暴雪直接寫入文字元件。", SAFE_LINE_2="插件不會在 Lua 中讀取或格式化光環層數。", AURA_TRACKERS="光環追蹤器",
        NEW="新增", DUPLICATE="複製", DELETE="刪除", PREVIEW="預覽", UNLOCK="解鎖", TRACKER_SETTINGS="追蹤器設定", NAME="名稱",
        AURA_IDS="光環 ID", UNIT="單位", ENABLED="啟用", HIDE_WHEN_MISSING="缺少時隱藏", APPLY_TRACKER="套用追蹤器",
        SELECTED_TRACKER="已選追蹤器：%s", CURSOR_OFFSET="游標偏移", CURSOR_OFFSET_DESC="將層數計數器放置在滑鼠游標周圍。",
        OFFSET_X="X 偏移", OFFSET_Y="Y 偏移", TEXT_APPEARANCE="文字外觀", TEXT_APPEARANCE_DESC="選擇層數數字的大小、外框和顏色。",
        FONT="字型", TEXT_SIZE="文字大小", OUTLINE_LABEL="外框", NONE="無", OUTLINE="外框", THICK_OUTLINE="粗外框", TEXT_COLOUR="文字顏色",
        AURA_DURATION="光環持續時間", AURA_DURATION_DESC="選擇數字下方的進度條或游標周圍的環形冷卻。", PROGRESS_DISPLAY="進度顯示",
        HORIZONTAL_BAR="水平條", CIRCLE_AROUND_CURSOR="游標周圍圓環", BAR_WIDTH="進度條寬度", BAR_HEIGHT="進度條高度",
        CIRCLE_SIZE="圓環大小", CIRCLE_THICKNESS="圓環粗細", PROGRESS_COLOUR="進度顏色", COLOUR="顏色",
        OPEN_MENU_DESC="使用下方按鈕開啟插件選單。", OPEN_MENU="開啟 lafee bdk bones stacks", MINIMAP_TOOLTIP="左鍵點擊開啟設定。",
        BONE_SHIELD="骸骨之盾", AURA_STACKS="光環層數", COPY_SUFFIX=" 副本",
    },
}

translations.esMX = translations.esES
local locale = type(GetLocale) == "function" and GetLocale() or "enUS"
for key, value in pairs(translations[locale] or {}) do L[key] = value end
NS.L = setmetatable(L, { __index = function(_, key) return key end })
